server:
  port: 8200
spring:
  application:
    name: oauth-serve

  redis:
    timeout: 10000s # 连接超时时间（毫秒）
    host: 192.168.190.129 #Redis服务器地址
    password: 123456 #密码
    port: 6379 #端口号
#    jedis:
#      pool:
#        max-wait: -1 #连接池最大阻塞等待时间
#        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
#        max-idle: 8 #连接池中的最大空闲连接
#        min-idle: 0 #连接池中的最小空闲连接
    lettuce:
      pool:
        max-wait: -1
        max-idle: 8
        max-active: 8
        min-idle: 0

#  main:
#    allow-bean-definition-overriding: true
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7100/eureka
    instance:
      prefer-ip-address: true
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/changgou.jks
    secret: changgou
    alias: changgou
    password: changgou

smsbao:
  username: zsls
  password: 123456
  httpurl: http://api.smsbao.com/sms
  time: 300
  contenthead: 【码麟科技有限公司】您的验证码是:{}, ５分钟内有效。若非本人操作请忽略此消息。